### ISSUE TITLE
🐛 [bug]: pipx is missing

### ISSUE THREAD

**Issue by mavimo** [raven-actions/actionlint#25]
### 🐛 What happened?

The upgrade to v2 require to have pipx already available on the workers, this may be true for github runners: 
 * https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md#package-management
but is not true for self-hosted runner.

### 🔬 How to reproduce?

Create a pipeline executed in a self-hosted worker (e.g. using act) where `pipx` is not installed

### 🏗️ Code Sample / Log

```Shell
Cache restored from key: actionlint-1.7.1-Linux-X64
Run actions/github-script@v7
Error: Unable to locate executable file: pipx. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
    at Object.<anonymous> (/runner/_work/_actions/actions/github-script/v7/dist/index.js:4381:27)
    at Generator.next (<anonymous>)
    at fulfilled (/runner/_work/_actions/actions/github-script/v7/dist/index.js:4234:58)
Error: Unhandled error: Error: Unable to locate executable file: pipx. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

### 🌌 Environment (actionlint action)

v2

### 🌌 Environment (actionlint)

1.7.1

### 🌌 Environment (GitHub Runner OS)

Linux

### 📈 Expected behavior

I suggest to check if pipx is installed and if missing evaluate to include it at runtime.
The changelog do not report it as requirement, so may be worth to mention it in the changelog/doc.

### 📜 Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by DariuszPorowski** [comment]
hi @mavimo 

It's mentioned in the README

![image](https://github.com/user-attachments/assets/706e6be5-bf60-40cb-9f67-7665ebf9f78b)

and changelog as well

![image](https://github.com/user-attachments/assets/f2364bf6-e8d9-45e0-9ac0-d6fc6ce89c9c)

and this is one of the reasons why is major bump

**Comment by mavimo** [comment]
@DariuszPorowski in the changelog was not highlighted as pre-requirement and the PR open dependabot do not report the changes in the readme.

Anyway I should have read the readme better, sorry for the noise.

**Comment by DariuszPorowski** [comment]
It's not a noise, it's actionable feedback for me to improve changelog in te future releases. Thanks 😊

**Comment by hamdrew** [comment]
I got bit by this, too, due to using a self-hosted runner. Turning this into Docker container might help alleviate dependency woes.  If you're interested in going that route, I could help contribute.
